--------------------------------------------------------
--  文件已创建 - 星期五-六月-03-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTHEN_ADMIN_LOGIN_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" 
   (	"ID" VARCHAR2(32 CHAR), 
	"ADMIN_ID" VARCHAR2(32 CHAR), 
	"ACCOUNT_TYPE" VARCHAR2(10 CHAR), 
	"LOGIN_ACCOUNT" VARCHAR2(32 CHAR), 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_DT" DATE DEFAULT SYSDATE, 
	"CREATED_SID" VARCHAR2(32 BYTE), 
	"UPDATED_SID" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"REMARK" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;

   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."ID" IS '账号ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."ADMIN_ID" IS '用户ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."ACCOUNT_TYPE" IS '登录账号类型：ID-身份证;MOBILE-手机;EMAIL-邮箱;USERNAME-用户名';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."LOGIN_ACCOUNT" IS '登录账号';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."CREATED_BY" IS '创建人ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."UPDATED_BY" IS '修改人ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."CREATED_DT" IS '创建时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."UPDATED_DT" IS '修改时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."CREATED_SID" IS '创建系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."UPDATED_SID" IS '修改系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"."REMARK" IS '备注';
   COMMENT ON TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT"  IS '服务人员登录账号';
--------------------------------------------------------
--  DDL for Table AUTHEN_ADMIN_SECRET_KEY
--------------------------------------------------------

  CREATE TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" 
   (	"ID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(32 BYTE), 
	"LOGIN_PASSORD" VARCHAR2(512 BYTE), 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_DT" DATE DEFAULT SYSDATE, 
	"CREATED_SID" VARCHAR2(32 BYTE), 
	"UPDATED_SID" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"REMARK" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;

   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."ID" IS '登录秘钥ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."USER_ID" IS '用户主账号';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."LOGIN_PASSORD" IS '密码';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."CREATED_BY" IS '创建人ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."UPDATED_BY" IS '修改人ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."CREATED_DT" IS '创建时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."UPDATED_DT" IS '修改时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."CREATED_SID" IS '创建系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."UPDATED_SID" IS '修改系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"."REMARK" IS '备注';
   COMMENT ON TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY"  IS '服务人员登录秘钥';
--------------------------------------------------------
--  DDL for Table AUTHEN_BIZ_APP
--------------------------------------------------------

  CREATE TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" 
   (	"ID" VARCHAR2(32 BYTE), 
	"APP_NAME" VARCHAR2(40 BYTE), 
	"APP_TYPE" VARCHAR2(10 BYTE), 
	"SECRT_KEY" VARCHAR2(512 BYTE), 
	"REDIRECT_URI_PREFIX" VARCHAR2(2000 BYTE), 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_DT" DATE DEFAULT SYSDATE, 
	"CREATED_SID" VARCHAR2(32 BYTE), 
	"UPDATED_SID" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"REMARK" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;

   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."ID" IS 'ID（同时作为编码）';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."APP_NAME" IS '系统中文名';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."APP_TYPE" IS '系统类型：WEBAPP - 普通web应用;IOSAPP - ios应用;ANDAPP - 安卓应用;NATIVE - 桌面应用';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."SECRT_KEY" IS '秘钥';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."REDIRECT_URI_PREFIX" IS '跳转地址前缀（仅WEB）';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."CREATED_BY" IS '创建用户主账号';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."UPDATED_BY" IS '修改用户主账号';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."CREATED_DT" IS '创建时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."UPDATED_DT" IS '修改时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."CREATED_SID" IS '创建系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."UPDATED_SID" IS '修改系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_BIZ_APP"."REMARK" IS '备注';
   COMMENT ON TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP"  IS '业务系统';
--------------------------------------------------------
--  DDL for Table AUTHEN_ENDUSER_LOGIN_ACCOUNT
--------------------------------------------------------

  CREATE TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" 
   (	"ID" VARCHAR2(32 CHAR), 
	"USER_ID" VARCHAR2(32 CHAR), 
	"ACCOUNT_TYPE" VARCHAR2(10 CHAR), 
	"LOGIN_ACCOUNT" VARCHAR2(32 CHAR), 
	"ACCOUNT_PASSORD" VARCHAR2(512 BYTE), 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_DT" DATE DEFAULT SYSDATE, 
	"CREATED_SID" VARCHAR2(32 BYTE), 
	"UPDATED_SID" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"REMARK" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;

   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."ID" IS '账号ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."USER_ID" IS '用户ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."ACCOUNT_TYPE" IS '登录账号类型：ID-身份证;MOBILE-手机;EMAIL-邮箱;USERNAME-用户名';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."LOGIN_ACCOUNT" IS '登录账号';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."ACCOUNT_PASSORD" IS '密码';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."CREATED_BY" IS '创建人ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."UPDATED_BY" IS '修改人ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."CREATED_DT" IS '创建时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."UPDATED_DT" IS '修改时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."CREATED_SID" IS '创建系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."UPDATED_SID" IS '修改系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"."REMARK" IS '备注';
   COMMENT ON TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT"  IS '登录登录账号';
--------------------------------------------------------
--  DDL for Table AUTHEN_ENDUSER_SECRET_KEY
--------------------------------------------------------

  CREATE TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" 
   (	"ID" VARCHAR2(32 BYTE), 
	"USER_ID" VARCHAR2(32 BYTE), 
	"LOGIN_PASSORD" VARCHAR2(512 BYTE), 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"UPDATED_DT" DATE DEFAULT SYSDATE, 
	"CREATED_SID" VARCHAR2(32 BYTE), 
	"UPDATED_SID" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"REMARK" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;

   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."ID" IS '登录秘钥ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."USER_ID" IS '用户主账号';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."LOGIN_PASSORD" IS '密码';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."CREATED_BY" IS '创建人ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."UPDATED_BY" IS '修改人ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."CREATED_DT" IS '创建时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."UPDATED_DT" IS '修改时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."CREATED_SID" IS '创建系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."UPDATED_SID" IS '修改系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"."REMARK" IS '备注';
   COMMENT ON TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY"  IS '最终用户登录秘钥';
--------------------------------------------------------
--  DDL for Table CM_ADMIN_INFO
--------------------------------------------------------

  CREATE TABLE "CM_USER_MANAGER"."CM_ADMIN_INFO" 
   (	"ADMIN_ID" VARCHAR2(32 BYTE), 
	"ADMIN_CODE" VARCHAR2(64 BYTE), 
	"ADMIN_NAME" VARCHAR2(64 BYTE), 
	"NICK_NAME" VARCHAR2(32 BYTE), 
	"PHOTO" VARCHAR2(1024 BYTE), 
	"NAME_PING" VARCHAR2(50 BYTE), 
	"SEX" VARCHAR2(1 BYTE), 
	"FOLK" VARCHAR2(2 BYTE), 
	"BIRTHDAY" DATE, 
	"ID_CARD" VARCHAR2(64 BYTE), 
	"CARD_PHOTO" VARCHAR2(1024 BYTE), 
	"UNIT_CODE" VARCHAR2(128 BYTE), 
	"NATIVE_PLACE" VARCHAR2(256 BYTE), 
	"BLOOD_TYPE" VARCHAR2(32 BYTE), 
	"WORK_TIME" VARCHAR2(32 BYTE), 
	"DEGREE" VARCHAR2(32 BYTE), 
	"GRADUATE" VARCHAR2(256 BYTE), 
	"ADDRESS" VARCHAR2(1024 BYTE), 
	"ZIP_CODE" VARCHAR2(32 BYTE), 
	"HOUSE_HODE_TYPE" VARCHAR2(32 BYTE), 
	"REALNAME_CHECKED" VARCHAR2(1 BYTE), 
	"MOBILE_CHECKED" VARCHAR2(1 BYTE), 
	"EMAIL_CHECKED" VARCHAR2(1 BYTE), 
	"FAITH" VARCHAR2(32 BYTE), 
	"PROVINCE" VARCHAR2(32 BYTE), 
	"CITY" VARCHAR2(32 BYTE), 
	"DISTRICT" VARCHAR2(32 BYTE), 
	"STREET" VARCHAR2(32 BYTE), 
	"HOMEPAGE" VARCHAR2(512 BYTE), 
	"ENABLE" VARCHAR2(1 BYTE), 
	"MOBILE" NUMBER(11,0), 
	"COMPANY_TELE" VARCHAR2(32 BYTE), 
	"HOME_TELE" VARCHAR2(32 BYTE), 
	"WECHAT" VARCHAR2(32 BYTE), 
	"QQ" VARCHAR2(32 BYTE), 
	"EMAIL" VARCHAR2(128 BYTE), 
	"EE" VARCHAR2(32 BYTE), 
	"DATA_TYPE_FLAG" VARCHAR2(1 BYTE) DEFAULT '2', 
	"REMARK" VARCHAR2(256 BYTE), 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"DELETED_BY" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"IS_DELETED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DELETED_DT" DATE, 
	"UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"UPDATED_DT" DATE, 
	"CREATED_SID" VARCHAR2(32 BYTE), 
	"UPDATED_SID" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;

   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."ADMIN_ID" IS '管理员ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."ADMIN_CODE" IS '用户编码';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."ADMIN_NAME" IS '真实姓名';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."NICK_NAME" IS '昵称';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."PHOTO" IS '用户头像';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."NAME_PING" IS '姓名拼音';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."SEX" IS '字典:SEX';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."FOLK" IS '字典:FOLK_CODE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."BIRTHDAY" IS '出生日期';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."ID_CARD" IS '身份证号';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."CARD_PHOTO" IS '证件照片';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."UNIT_CODE" IS '单位编码';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."NATIVE_PLACE" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."BLOOD_TYPE" IS '血型';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."WORK_TIME" IS '参加工作时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."DEGREE" IS '字典:DEGREE_CODE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."GRADUATE" IS '编码:CM_COMPANY_INFO';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."ADDRESS" IS '现住址';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."ZIP_CODE" IS '邮政编码';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."HOUSE_HODE_TYPE" IS '户口性质';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."REALNAME_CHECKED" IS '身份证信息(姓名\性别\出生日期\地址\身份证号等身份证信息)';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."MOBILE_CHECKED" IS '手机是否验证';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."EMAIL_CHECKED" IS '邮箱是否验证';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."FAITH" IS '字典FAITH_CODE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."PROVINCE" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."CITY" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."DISTRICT" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."STREET" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."HOMEPAGE" IS '个人主页';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."ENABLE" IS '字典:ENABLE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."MOBILE" IS '手机';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."COMPANY_TELE" IS '公司电话';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."HOME_TELE" IS '家庭电话';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."WECHAT" IS '微信';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."QQ" IS 'QQ';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."EMAIL" IS '电子邮箱';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."EE" IS 'EE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."DATA_TYPE_FLAG" IS '数据类型标示 ：1-旧数据 2-新数据';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."REMARK" IS '备注';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."CREATED_DT" IS '创建时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."CREATED_BY" IS '创建用户';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."DELETED_BY" IS '删除用户';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."IS_DELETED" IS '删除标识';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."DELETED_DT" IS '删除时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."UPDATED_BY" IS '修改用户';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."UPDATED_DT" IS '修改时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."CREATED_SID" IS '创建系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_ADMIN_INFO"."UPDATED_SID" IS '修改系统ID';
   COMMENT ON TABLE "CM_USER_MANAGER"."CM_ADMIN_INFO"  IS '用户信息';
--------------------------------------------------------
--  DDL for Table CM_USER_INFO
--------------------------------------------------------

  CREATE TABLE "CM_USER_MANAGER"."CM_USER_INFO" 
   (	"USER_ID" VARCHAR2(32 BYTE), 
	"USER_CODE" VARCHAR2(64 BYTE), 
	"USER_NAME" VARCHAR2(64 BYTE), 
	"NICK_NAME" VARCHAR2(32 BYTE), 
	"PHOTO" VARCHAR2(1024 BYTE), 
	"NAME_PING" VARCHAR2(50 BYTE), 
	"SEX" VARCHAR2(1 BYTE), 
	"FOLK" VARCHAR2(2 BYTE), 
	"BIRTHDAY" DATE, 
	"ID_CARD" VARCHAR2(64 BYTE), 
	"CARD_PHOTO" VARCHAR2(1024 BYTE), 
	"UNIT_CODE" VARCHAR2(128 BYTE), 
	"NATIVE_PLACE" VARCHAR2(256 BYTE), 
	"BLOOD_TYPE" VARCHAR2(32 BYTE), 
	"WORK_TIME" VARCHAR2(32 BYTE), 
	"DEGREE" VARCHAR2(32 BYTE), 
	"GRADUATE" VARCHAR2(256 BYTE), 
	"ADDRESS" VARCHAR2(1024 BYTE), 
	"ZIP_CODE" VARCHAR2(32 BYTE), 
	"HOUSE_HODE_TYPE" VARCHAR2(32 BYTE), 
	"REALNAME_CHECKED" VARCHAR2(1 BYTE), 
	"MOBILE_CHECKED" VARCHAR2(1 BYTE), 
	"EMAIL_CHECKED" VARCHAR2(1 BYTE), 
	"FAITH" VARCHAR2(32 BYTE), 
	"PROVINCE" VARCHAR2(32 BYTE), 
	"CITY" VARCHAR2(32 BYTE), 
	"DISTRICT" VARCHAR2(32 BYTE), 
	"STREET" VARCHAR2(32 BYTE), 
	"HOMEPAGE" VARCHAR2(512 BYTE), 
	"ENABLE" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"MOBILE" NUMBER(11,0), 
	"COMPANY_TELE" VARCHAR2(32 BYTE), 
	"HOME_TELE" VARCHAR2(32 BYTE), 
	"WECHAT" VARCHAR2(32 BYTE), 
	"QQ" VARCHAR2(32 BYTE), 
	"EMAIL" VARCHAR2(128 BYTE), 
	"EE" VARCHAR2(32 BYTE), 
	"DATA_TYPE_FLAG" VARCHAR2(1 BYTE) DEFAULT '2', 
	"REMARK" VARCHAR2(256 BYTE), 
	"CREATED_DT" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(32 BYTE), 
	"DELETED_BY" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"IS_DELETED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"DELETED_DT" DATE, 
	"UPDATED_BY" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE', 
	"UPDATED_DT" DATE DEFAULT SYSDATE, 
	"CREATED_SID" VARCHAR2(32 BYTE), 
	"UPDATED_SID" VARCHAR2(32 BYTE) DEFAULT 'NEVER_CHANGE'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;

   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."USER_ID" IS '用户ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."USER_CODE" IS '用户编码';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."USER_NAME" IS '真实姓名';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."NICK_NAME" IS '昵称';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."PHOTO" IS '用户头像';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."NAME_PING" IS '姓名拼音';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."SEX" IS '字典:SEX';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."FOLK" IS '字典:FOLK_CODE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."BIRTHDAY" IS '出生日期';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."ID_CARD" IS '身份证号';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."CARD_PHOTO" IS '证件照片';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."UNIT_CODE" IS '单位编码';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."NATIVE_PLACE" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."BLOOD_TYPE" IS '血型';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."WORK_TIME" IS '参加工作时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."DEGREE" IS '字典:DEGREE_CODE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."GRADUATE" IS '编码:CM_COMPANY_INFO';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."ADDRESS" IS '现住址';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."ZIP_CODE" IS '邮政编码';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."HOUSE_HODE_TYPE" IS '户口性质';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."REALNAME_CHECKED" IS '身份证信息(姓名\性别\出生日期\地址\身份证号等身份证信息)';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."MOBILE_CHECKED" IS '手机是否验证';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."EMAIL_CHECKED" IS '邮箱是否验证';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."FAITH" IS '字典FAITH_CODE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."PROVINCE" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."CITY" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."DISTRICT" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."STREET" IS '区域码表:CM_AREA';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."HOMEPAGE" IS '个人主页';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."ENABLE" IS '字典:ENABLE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."MOBILE" IS '手机';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."COMPANY_TELE" IS '公司电话';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."HOME_TELE" IS '家庭电话';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."WECHAT" IS '微信';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."QQ" IS 'QQ';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."EMAIL" IS '电子邮箱';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."EE" IS 'EE';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."DATA_TYPE_FLAG" IS '数据类型标示 ：1-旧数据 2-新数据';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."REMARK" IS '备注';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."CREATED_DT" IS '创建时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."CREATED_BY" IS '创建用户';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."DELETED_BY" IS '删除用户';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."IS_DELETED" IS '删除标识';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."DELETED_DT" IS '删除时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."UPDATED_BY" IS '修改用户';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."UPDATED_DT" IS '修改时间';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."CREATED_SID" IS '创建系统ID';
   COMMENT ON COLUMN "CM_USER_MANAGER"."CM_USER_INFO"."UPDATED_SID" IS '修改系统ID';
   COMMENT ON TABLE "CM_USER_MANAGER"."CM_USER_INFO"  IS '用户信息';
--------------------------------------------------------
--  DDL for Index PK_AUTHEN_ADMIN_LOGIN_ACCOUNT
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."PK_AUTHEN_ADMIN_LOGIN_ACCOUNT" ON "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index AK_UNIQUE_LOGIN_ACCOU_AUTHEN_A
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."AK_UNIQUE_LOGIN_ACCOU_AUTHEN_A" ON "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" ("LOGIN_ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index AK_UNIQUE_ACCOUNT_ID__AUTHEN_A
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."AK_UNIQUE_ACCOUNT_ID__AUTHEN_A" ON "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" ("ADMIN_ID", "ACCOUNT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index PK_AUTHEN_ADMIN_SECRET_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."PK_AUTHEN_ADMIN_SECRET_KEY" ON "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index AK_UNIQUE_MAIN_ACCOUN_AUTHEN_A
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."AK_UNIQUE_MAIN_ACCOUN_AUTHEN_A" ON "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index PK_AUTHEN_BIZ_APP
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."PK_AUTHEN_BIZ_APP" ON "CM_USER_MANAGER"."AUTHEN_BIZ_APP" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index AK_UNIQUE_SSO_SYS_AUTHEN_B
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."AK_UNIQUE_SSO_SYS_AUTHEN_B" ON "CM_USER_MANAGER"."AUTHEN_BIZ_APP" ("APP_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index PK_AUTHEN_ENDUSER_LOGIN_ACCOUN
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."PK_AUTHEN_ENDUSER_LOGIN_ACCOUN" ON "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index AK_UNIQUE_LOGIN_ACCOU_AUTHEN_E
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."AK_UNIQUE_LOGIN_ACCOU_AUTHEN_E" ON "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" ("LOGIN_ACCOUNT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index AK_UNIQUE_ACCOUNT_ID__AUTHEN_E
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."AK_UNIQUE_ACCOUNT_ID__AUTHEN_E" ON "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" ("USER_ID", "ACCOUNT_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index PK_AUTHEN_ENDUSER_SECRET_KEY
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."PK_AUTHEN_ENDUSER_SECRET_KEY" ON "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index AK_UNIQUE_MAIN_ACCOUN_AUTHEN_E
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."AK_UNIQUE_MAIN_ACCOUN_AUTHEN_E" ON "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index PK_CM_ADMIN_INFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."PK_CM_ADMIN_INFO" ON "CM_USER_MANAGER"."CM_ADMIN_INFO" ("ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  DDL for Index PK_CM_USER_INFO
--------------------------------------------------------

  CREATE UNIQUE INDEX "CM_USER_MANAGER"."PK_CM_USER_INFO" ON "CM_USER_MANAGER"."CM_USER_INFO" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER" ;
--------------------------------------------------------
--  Constraints for Table AUTHEN_ADMIN_LOGIN_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" ADD CONSTRAINT "AK_UNIQUE_ACCOUNT_ID__AUTHEN_A" UNIQUE ("ADMIN_ID", "ACCOUNT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" ADD CONSTRAINT "AK_UNIQUE_LOGIN_ACCOU_AUTHEN_A" UNIQUE ("LOGIN_ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" ADD CONSTRAINT "PK_AUTHEN_ADMIN_LOGIN_ACCOUNT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("UPDATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("CREATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("UPDATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("LOGIN_ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("ACCOUNT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_LOGIN_ACCOUNT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTHEN_ADMIN_SECRET_KEY
--------------------------------------------------------

  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" ADD CONSTRAINT "AK_UNIQUE_MAIN_ACCOUN_AUTHEN_A" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" ADD CONSTRAINT "PK_AUTHEN_ADMIN_SECRET_KEY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" MODIFY ("UPDATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" MODIFY ("CREATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" MODIFY ("UPDATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" MODIFY ("LOGIN_PASSORD" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ADMIN_SECRET_KEY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTHEN_BIZ_APP
--------------------------------------------------------

  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" ADD CONSTRAINT "AK_UNIQUE_SSO_SYS_AUTHEN_B" UNIQUE ("APP_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" ADD CONSTRAINT "PK_AUTHEN_BIZ_APP" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("UPDATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("CREATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("UPDATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("SECRT_KEY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("APP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("APP_NAME" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_BIZ_APP" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTHEN_ENDUSER_LOGIN_ACCOUNT
--------------------------------------------------------

  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" ADD CONSTRAINT "AK_UNIQUE_ACCOUNT_ID__AUTHEN_E" UNIQUE ("USER_ID", "ACCOUNT_TYPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" ADD CONSTRAINT "AK_UNIQUE_LOGIN_ACCOU_AUTHEN_E" UNIQUE ("LOGIN_ACCOUNT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" ADD CONSTRAINT "PK_AUTHEN_ENDUSER_LOGIN_ACCOUN" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("UPDATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("CREATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("UPDATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("ACCOUNT_PASSORD" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("LOGIN_ACCOUNT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("ACCOUNT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_LOGIN_ACCOUNT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTHEN_ENDUSER_SECRET_KEY
--------------------------------------------------------

  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" ADD CONSTRAINT "AK_UNIQUE_MAIN_ACCOUN_AUTHEN_E" UNIQUE ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" ADD CONSTRAINT "PK_AUTHEN_ENDUSER_SECRET_KEY" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" MODIFY ("UPDATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" MODIFY ("CREATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" MODIFY ("UPDATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" MODIFY ("LOGIN_PASSORD" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."AUTHEN_ENDUSER_SECRET_KEY" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CM_ADMIN_INFO
--------------------------------------------------------

  ALTER TABLE "CM_USER_MANAGER"."CM_ADMIN_INFO" ADD CONSTRAINT "PK_CM_ADMIN_INFO" PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."CM_ADMIN_INFO" MODIFY ("CREATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_ADMIN_INFO" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_ADMIN_INFO" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_ADMIN_INFO" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_ADMIN_INFO" MODIFY ("DATA_TYPE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_ADMIN_INFO" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CM_USER_INFO
--------------------------------------------------------

  ALTER TABLE "CM_USER_MANAGER"."CM_USER_INFO" ADD CONSTRAINT "PK_CM_USER_INFO" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CM_USER_MANAGER"  ENABLE;
  ALTER TABLE "CM_USER_MANAGER"."CM_USER_INFO" MODIFY ("CREATED_SID" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_USER_INFO" MODIFY ("IS_DELETED" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_USER_INFO" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_USER_INFO" MODIFY ("CREATED_DT" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_USER_INFO" MODIFY ("DATA_TYPE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "CM_USER_MANAGER"."CM_USER_INFO" MODIFY ("USER_ID" NOT NULL ENABLE);
